# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='item',
            new_name='uploader',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked_items', to='belt.User'),
        ),
    ]
